name: ci-pipeline 

on:
  push:
    branches:  ["none"]
  workflow_dispatch:

jobs:
  ci_build: 
    name: CI build
    runs-on: [selfhosted,self-hosted,windows]
    steps:
    - uses: actions/checkout@v4
    - name: gitleaks
      uses: actions/gitleaks/gitleaks-action@v2s
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'     # or adopt, zulu, etc.
        java-version: '11'          # adjust Java version

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: maven-build
      run: mvn clean install  -Dskiptests=true
 
