name: CI Pipeline

on:
  push:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: dev
        type: choice
        description: "deployment Environment"
        options:
          - dev
          - uat
          - prod
  

concurrency:
  group: ${{ github.ref}}
  cancel-in-progress: true
  
jobs:
  build-and-scan:
    runs-on:  hosted
    env: 
      DOCKER_IMAGE: organisation/backend:${{ github.ref }}
    strategy:
      matrix: 
        os: [java]
        version: [11]
        fail-fall: [false]